### PR TITLE
Track the code coverage

### PR DESCRIPTION
**Pull request by sgl0v**
Integrated with [coveralls.io](coveralls.io) to track the code coverage. You should create the user account at coveralls.io before merging.

### CODE REVIEW

**Comment by artman** [comment]
Thanks! Mind rebasing on master and resubmitting your PR onto the development branch?

**Comment by sgl0v** [comment]
Done.

**Comment by artman** [comment]
Thanks. Just one more request. If you could modify this PR to merge into the "development" branch, not the master branch. That'd be rad.

**Comment by sgl0v** [comment]
There is no way to change the branch. In the end I closed this PR and created the new [one](https://github.com/uber/signals-ios/pull/16).

**Pull request closed without merging**
