### PR TITLE
Fix Array bridges error && update swift3 syntax

### PR DESCRIPTION
**Pull request by zhongwuzw**

### CODE REVIEW

**Comment by zhongwuzw** [comment]
#36

**Comment by artman** [comment]
Thanks @zhongwuzw. There's some legit unit test failures happening with your PR:

```
❌  /Users/travis/build/uber/signals-ios/UberSignalsTests/SwiftTests.swift:112:44: cannot call value of non-function type '((String!, NSNumber!) -> Void)!'
        observer.onSwiftDoubleSignal.fire()("1", NSNumber(value: 2))
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
** BUILD FAILED **
```

**Comment by zhongwuzw** [comment]
@artman , I have been updated to `Swift3`.

**Comment by artman** [comment]
@zhongwuzw, with that change 8.x simulators aren't available anymore. Mind changing the .travis.config and just remove the 8.x simulators for CI to pass this PR? Thanks!

**Comment by zhongwuzw** [comment]
@artman , I update the travis.yml to remove iOS8.x

**Comment by artman** [comment]
Thanks!

**Pull request merged**
